# passar trace=true na url para ver o stacktrace
server:
  error:
    include-stacktrace: on_param

# String de conexão com o banco de dados

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

# Essa configuração, é para que o log seja apresentado no padão do Spring.
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG